export const REQUEST_TYPES = {
  ADD_CAB: 'ADD_CAB',
  UPDATE_CAB: 'UPDATE_CAB',

  ADD_HOTEL: 'ADD_HOTEL',
  UPDATE_HOTEL: 'UPDATE_HOTEL',

  ADD_ITINERARY: 'ADD_ITINERARY',
  PACKAGE_APPROVAL: 'PACKAGE_APPROVAL',

  OTHER: 'OTHER',
};

export const REQUEST_TYPE_LABELS = {
  ADD_CAB: 'Add Cab',
  UPDATE_CAB: 'Update Cab',


  ADD_HOTEL: 'Add Hotel',
  UPDATE_HOTEL: 'Update Hotel',


  ADD_ITINERARY: 'Add Itinerary',

  PACKAGE_APPROVAL: 'Package Approval',

  OTHER: 'Other',
};

export const REQUEST_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const NOTIFICATION_TYPES = {
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_APPROVED: 'REQUEST_APPROVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
};

export const REQUEST_TYPE_VALUES = Object.values(REQUEST_TYPES);
export const REQUEST_STATUS_VALUES = Object.values(REQUEST_STATUSES);

export const getRequestTypeLabel = (type) =>
  REQUEST_TYPE_LABELS[type] || String(type || 'Request').replace(/_/g, ' ');
