export const REQUEST_TYPES = {
  ADD_CAB: 'ADD_CAB',
  UPDATE_CAB: 'UPDATE_CAB',
  REMOVE_CAB: 'REMOVE_CAB',

  ADD_HOTEL: 'ADD_HOTEL',
  UPDATE_HOTEL: 'UPDATE_HOTEL',
  REMOVE_HOTEL: 'REMOVE_HOTEL',

  ADD_ITINERARY: 'ADD_ITINERARY',
  UPDATE_ITINERARY: 'UPDATE_ITINERARY',
  REMOVE_ITINERARY: 'REMOVE_ITINERARY',

  ADD_ACTIVITY: 'ADD_ACTIVITY',
  UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',

  PRICE_CHANGE: 'PRICE_CHANGE',
  DISCOUNT_REQUEST: 'DISCOUNT_REQUEST',

  PACKAGE_APPROVAL: 'PACKAGE_APPROVAL',

  OTHER: 'OTHER',
};

export const REQUEST_TYPE_LABELS = {
  ADD_CAB: 'Add Cab',
  UPDATE_CAB: 'Update Cab',
  REMOVE_CAB: 'Remove Cab',

  ADD_HOTEL: 'Add Hotel',
  UPDATE_HOTEL: 'Update Hotel',
  REMOVE_HOTEL: 'Remove Hotel',

  ADD_ITINERARY: 'Add Itinerary',
  UPDATE_ITINERARY: 'Update Itinerary',
  REMOVE_ITINERARY: 'Remove Itinerary',

  ADD_ACTIVITY: 'Add Activity',
  UPDATE_ACTIVITY: 'Update Activity',
  REMOVE_ACTIVITY: 'Remove Activity',

  PRICE_CHANGE: 'Price Change',
  DISCOUNT_REQUEST: 'Discount Request',

  PACKAGE_APPROVAL: 'Package Approval',

  OTHER: 'Other',
};

export const REQUEST_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const NOTIFICATION_TYPES = {
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_APPROVED: 'REQUEST_APPROVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
};

export const REQUEST_TYPE_VALUES = Object.values(REQUEST_TYPES);
export const REQUEST_STATUS_VALUES = Object.values(REQUEST_STATUSES);

export const getRequestTypeLabel = (type) =>
  REQUEST_TYPE_LABELS[type] || String(type || 'Request').replace(/_/g, ' ');
